Track frame sizes along with frames
dask/distributed pull request #4593
Opened 2021-03-15 23:01 UTC by jakirkham

Should cutdown on the number of `nbytes` calls to 1 per frame as opposed to a couple as before.

- [ ] Closes #xxxx
- [ ] Tests added / passed
- [ ] Passes `black distributed` / `flake8 distributed`

2021-03-16 08:19 UTC, madsbk requested changes
Looks good @jakirkham, you just need to return `frames_nbytes_total` as well:
https://github.com/dask/distributed/blob/644aebb8f08d0fd475c0ce49082342c9eca13e7f/distributed/comm/tcp.py#L290

2021-03-16 17:42 UTC, jakirkham commented
Oops 🤦‍♂️ Knew I was missing something silly. Thanks Mads! 😄

Should be fixed now 🙂

2021-03-17 08:43 UTC, madsbk approved these changes

2021-03-17 14:20 UTC, quasiben approved these changes
Thanks @jakirkham and @madsbk

2021-03-17 14:20 UTC, merged