Harden vs. TaskState collisions
dask/distributed pull request #6593
Opened 2022-06-17 15:26 UTC by crusaderky

2022-06-20 17:26 UTC, crusaderky commented
This PR accidentally relates with #6585, which is dealing with a very similar design issue on the scheduler side:
- the `SchedulerState` holding sets of `scheduler.WorkerState` objects there
- the `worker_state_machine.WorkerState` holding sets of `TaskState` objects here

In both cases, there *should* never be a case of duplicate objects in the set but we can't enforce it through a key.
We should agree on a coherent design for the two.

2022-06-21 09:36 UTC, fjetter requested changes
We should not merge this until the conversation in https://github.com/dask/distributed/pull/6585#issuecomment-1161504498 is settled.

2022-06-21 12:25 UTC, fjetter commented on distributed/worker_state_machine.py
> +        return id(self)
Is this change required to get the validation passing?

2022-06-21 18:33 UTC, gjoseph92 commented on distributed/worker_state_machine.py
> +        return id(self)
Strictly speaking, both `__eq__` and `__hash__` are unnecessary to get the behavior we want:

> User-defined classes have [`__eq__()`](https://docs.python.org/3/reference/datamodel.html#object.__eq__) and [`__hash__()`](https://docs.python.org/3/reference/datamodel.html#object.__hash__) methods by default; with them, all objects compare unequal (except with themselves) and `x.__hash__()` returns an appropriate value such that `x == y` implies both that `x is y` and `hash(x) == hash(y)`.
https://docs.python.org/3/reference/datamodel.html#object.__hash__

I'd kinda prefer to not implement them at all and just use the defaults. We can keep a comment explaining this, but having the explicit methods feels redundant.

2022-06-25 15:50 UTC, merged