Support MIG parsing during CUDA context creation in UCX initialization
dask/distributed pull request #6720
Opened 2022-07-12 21:08 UTC by pentschev

Some issues relating to MIG often arise because of lack of automated CI for that, as it requires specialized hardware that isn't currently available in gpuCI. This PR addresses errors reported recently, see https://github.com/rapidsai/dask-cuda/issues/583#issuecomment-1181505348 . Depends on #6678 .

- [ ] Tests added / passed
- [ ] Passes `pre-commit run --all-files`

2022-07-21 14:16 UTC, wence- commented
#6678 is now in, could you rebase to drop those commits?

2022-07-21 18:40 UTC, wence- requested changes
Mostly minor docstring fixes, but I think when getting the MIG devices we should do a bit more error checking if possible.

2022-10-28 19:18 UTC, pentschev reviewed
Thanks @wence- for the great review. I think I've addressed or responded to all your suggestions, would you mind taking another look when you have some time?

2022-10-31 09:15 UTC, wence- commented on distributed/comm/tests/test_ucx.py
> +        pytest.skip("No CUDA devices in non-MIG mode available.")
Or perhaps, ["asking for forgiveness"](https://docs.python.org/3.5/glossary.html#term-eafp)

```python
try:
    device_index, *_ = (i for i in range(device_get_count()) if get_device_mig_mode(i)[0] == 0)
except ValueError:
    pytest.skip("No CUDA devices in non-MIG mode available.")
```

2022-10-31 09:19 UTC, wence- commented on distributed/diagnostics/nvml.py
> +        # Validate UUID, get index and UUID as seen with `nvidia-smi -L`
Makes sense, thanks.

2022-10-31 09:20 UTC, wence- commented on distributed/diagnostics/nvml.py
> +        uuid = pynvml.nvmlDeviceGetUUID(uuid_handle)
As above, let's rely on nvml errors, thanks.

2022-10-31 13:15 UTC, pentschev commented on distributed/comm/tests/test_ucx.py
> +        pytest.skip("No CUDA devices in non-MIG mode available.")
Thanks @wence- for the suggestion. I've included the last one for this test. I had also to do a few more changes to this test, details in the commit message of https://github.com/dask/distributed/pull/6720/commits/d5d5e71a3e8a6f459f0af58a98425e52b81ab96f .

2022-10-31 16:42 UTC, wence- commented on distributed/comm/tests/test_ucx.py
> +        pytest.skip("No CUDA devices in non-MIG mode available.")
Thanks!

2022-10-31 16:43 UTC, wence- commented
Can you check the gpuci failures here? https://gpuci.gpuopenanalytics.com/job/dask/job/distributed/job/prb/job/distributed-prb/5098/

2022-10-31 20:39 UTC, pentschev commented
> Can you check the gpuci failures here? https://gpuci.gpuopenanalytics.com/job/dask/job/distributed/job/prb/job/distributed-prb/5098/

Yeah, I'm still trying to figure those. Unfortunately the tests pass if you run them alone, but there seems to be some leakage from previous tests that cause that to fail. I'll keep trying.

2022-11-01 09:41 UTC, wence- commented
> Yeah, I'm still trying to figure those. Unfortunately the tests pass if you run them alone, but there seems to be some leakage from previous tests that cause that to fail. I'll keep trying.

Seems like pyvml returns the PID of the handle in the host system, not the PID in the container :(.

(In a container)
```python
In [1]: import numba.cuda

In [2]: import pynvml

In [3]: numba.cuda.current_context()
Out[3]: <CUDA context c_void_p(94546817482160) of device 0>

In [4]: pynvml.nvmlInit()

In [5]: handle = pynvml.nvmlDeviceGetHandleByIndex(0)

In [6]: process, = pynvml.nvmlDeviceGetComputeRunningProcesses_v2(handle)

In [7]: process.pid
Out[7]: 32487

In [8]: import os

In [9]: os.getpid()
Out[9]: 8611
```
Outside the container:
```
$ nvidia-smi
...
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     32487      C   ...da/envs/ucx/bin/python3.9      303MiB |
+-----------------------------------------------------------------------------+
```

2022-11-01 11:19 UTC, wence- commented on distributed/comm/ucx.py
>              _warn_existing_cuda_context(pre_existing_cuda_context, os.getpid())
```suggestion
            _warn_existing_cuda_context(pre_existing_cuda_context.device_info, os.getpid())
```

2022-11-01 11:45 UTC, wence- commented on distributed/utils_test.py
> +
Aside, I think we should move this fixture to the `test_ucx.py` testfile and make it an `autouse=True` fixture. Then when writing a test we don't have to remember to require it.

2022-11-01 14:23 UTC, wence- commented on distributed/utils_test.py
> +
Ah, OK, scratch that then.

2022-11-01 14:25 UTC, wence- commented on distributed/utils_test.py
> +    distributed.comm.ucx.ucp = None
Is it not sufficient to just get the device associated with the current context and reset it? (As my changed suggestion does). TBH, I don't really know how MIG devices work with the primary contexts created by the runtime API, but primary context management only talks about device ids.

This is low priority though, and given the issues with containerisation around probing the resource management layer, we could just skip this test that way.

2022-11-02 17:28 UTC, pentschev commented
Alright, I now marked both CUDA context tests to xfail and gpuCI is passing. Could you take one more look when you have the chance @wence- ?

2022-11-03 15:03 UTC, pentschev commented
All 3 failing tests are the same as reported in https://github.com/dask/distributed/issues/7208 . I'm not sure whether codecov  is an artefact of the failing tests or something else, but I don't believe this PR has potential to affect it so heavily, so not really sure what is happening there.

2022-11-03 15:20 UTC, pentschev commented
@fjetter @jrbourbeau wondering if you could help us figure if something is wrong with codecov, I don't believe this PR alone should decrease coverage, and if I try to open the [codecov report for this PR](https://app.codecov.io/gh/dask/distributed/pull/6720) and click on any file to expand it, nothing shows up. Is there some potential issue ongoing with codecov, or am I doing something potentially wrong?

2022-11-03 15:40 UTC, wence- commented
> @fjetter @jrbourbeau wondering if you could help us figure if something is wrong with codecov, I don't believe this PR alone should decrease coverage, and if I try to open the [codecov report for this PR](https://app.codecov.io/gh/dask/distributed/pull/6720) and click on any file to expand it, nothing shows up. Is there some potential issue ongoing with codecov, or am I doing something potentially wrong?

For some reason (https://github.com/dask/distributed/actions/runs/3379719559/jobs/5611652549#step:20:36) the coverage failed to upload.

2022-11-03 15:45 UTC, wence- commented
> I don't believe this PR alone should decrease coverage

All the mig-based code (which is more lines, I think) [e.g. https://github.com/dask/distributed/pull/6720/files#diff-457ccaa4d4a70945b095c0460229791e8142c269e9ec781b98ab6d1b1925fd8cR201-R217] will be untested because nothing runs with mig devices. Moreover, I think because GPUCI doesn't interact with codecov, the assumption will be that all the `comm/ucx.py` and `diagnostics/nvml.py` files have zero coverage. This PR has a net increase in the number of lines in those files (so the total number of uncovered lines goes up, and coverage goes down).

2022-11-03 15:51 UTC, wence- commented
A big hammer would be to ignore those files, per https://docs.codecov.com/docs/ignoring-paths (although those patterns don't look like regexes to me)

```patch
diff --git a/codecov.yml b/codecov.yml
index 319545ae..bf003804 100644
--- a/codecov.yml
+++ b/codecov.yml
@@ -1,6 +1,12 @@
 codecov:
   require_ci_to_pass: yes
 
+ignore:
+  # These files exercise GPU functionality which is tested but doesn't
+  # interact with coverage reports, so we ignore them
+  - "distributed/comm/ucx.py"
+  - "distributed/diagnostics/nvml.py"
+  
 coverage:
   precision: 2
   round: down
```

2022-11-03 16:10 UTC, pentschev commented
> All the mig-based code (which is more lines, I think) (e.g. https://github.com/dask/distributed/pull/6720/files#diff-457ccaa4d4a70945b095c0460229791e8142c269e9ec781b98ab6d1b1925fd8cR201-R217) will be untested because nothing runs with mig devices.

Right, but codecov complains the net change is of -0.75%.

> Moreover, I think because GPUCI doesn't interact with codecov, the assumption will be that all the comm/ucx.py and diagnostics/nvml.py files have zero coverage. This PR has a net increase in the number of lines in those files (so the total number of uncovered lines goes up, and coverage goes down).

So even if none of the lines added by this PR are actually seen by codecov, I wouldn't amount to 0.75% of the entire Distributed codebase. Finally, if you look at the whole codecov list many files that aren't at all related to this PR are considered (e.g., `pytorch.py` decreased by 97.73%). With that said, I believe the problem the failure of codecov uploading files sounds more plausible, as you mentioned in https://github.com/dask/distributed/pull/6720#issuecomment-1302301864 .

2022-11-03 16:19 UTC, pentschev commented
@wence- I pushed part of the changes you suggested in https://github.com/dask/distributed/pull/6720#issuecomment-1302316138. NVML is actually tested by some of the CPU workflows [here](https://github.com/dask/distributed/blob/main/continuous_integration/environment-3.8.yaml#L30) and [here](https://github.com/dask/distributed/blob/aa1c6d858fc5a3e6b6a3276686f469ef25af14eb/continuous_integration/environment-3.9.yaml#L31), so we don't want to ignore it.

2022-11-15 12:40 UTC, wence- approved these changes

2022-11-15 15:28 UTC, jacobtomlinson approved these changes
Thanks for the review @wence-. This looks good to me, failing tests seem unrelated.

2022-11-15 15:29 UTC, merged