Dump `has_what`, `missing_dep_flight`
dask/distributed pull request #6830
Opened 2022-08-04 19:51 UTC by gjoseph92

Happened to notice these were missing from cluster dumps

- [x] Tests added / passed
- [x] Passes `pre-commit run --all-files`

2022-08-04 20:50 UTC, crusaderky approved these changes

2022-08-04 20:51 UTC, crusaderky requested changes
A test is failing

2022-08-04 23:16 UTC, gjoseph92 commented
Just https://github.com/dask/distributed/issues/6731. @crusaderky final review?

2022-08-05 22:03 UTC, crusaderky approved these changes

2022-08-05 22:03 UTC, merged

2022-08-05 22:03 UTC, crusaderky commented
thank you!