Naming conventions for Prometheus counters
dask/distributed pull request #7374
Opened 2022-12-06 16:40 UTC by hendrikmakait

Follows the OpenMetrics specification (https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#suffixes) and avoids `_total` suffixes on metric families which will be automatically added to `Counter`s (https://github.com/prometheus/client_python#counter). This makes it easier to follow the rules applied to Prometheus metric names and helps resolve issues in dask/dask/pull/9696.

- [x] Tests added / passed
- [x] Passes `pre-commit run --all-files`

2022-12-08 13:35 UTC, fjetter commented
I like this in principle but this is a breaking change and we currently don't have a proper mechanism for lifecycling prometheus metrics.

Is anybody aware of a good pattern to do this? The only thing I can think of is to introduce a `prometheus_metrics_version` config we can use to manage this and issue deprecation warnings and toggle certain metrics on/off. Those who rely on compatibility can then set this and get proper warnings. Thoughts?

cc @jacobtomlinson

2022-12-09 12:58 UTC, crusaderky requested changes

2022-12-09 12:58 UTC, crusaderky commented on distributed/http/scheduler/prometheus/semaphore.py
>              labels=["name"],
```suggestion
            labels=["name"],
            unit="seconds",
```
Cosmetic nitpick. The output name remains the same

2022-12-09 12:58 UTC, crusaderky commented on distributed/http/scheduler/prometheus/semaphore.py
> +            self.build_name("average_pending_lease_time_seconds"),
```suggestion
            self.build_name("average_pending_lease_time"),
```

2025-09-01 14:34 UTC, closed without merging