Promote null types during concat_tables (#7837).
dask/distributed pull request #7922
Opened 2023-06-15 16:30 UTC by detroyejr

Ran into this issue after upgrading to 2023.6. Luckily, it's an easy fix.

Columns with sparse data can have partitions with empty/null columns. This creates a conflict of data types between the partitions and an error during concatenation.

Closes #7837

- [ x] Tests added / passed
- [ x] Passes `pre-commit run --all-files`

2023-06-15 16:30 UTC, GPUtester commented
Can one of the admins verify this patch?

Admins can comment `ok to test` to allow this one PR to run or `add to allowlist` to allow all future PRs from the same author to run.

2023-06-15 16:33 UTC, jrbourbeau reviewed
Thanks @detroyejr! 

@hendrikmakait @phofl do either of you have bandwidth to review?

2023-06-15 16:34 UTC, jrbourbeau reviewed
Also, could you add a small test for this? Something similar to the snippet in the original issue should be sufficient

2023-06-16 00:02 UTC, detroyejr commented
Test added. Seems to do the trick, but let me know if you have any feedback.

2023-06-16 09:23 UTC, phofl reviewed
Test generally looks good to me and should cover the bug. 

Needs another pair of eyes from someone who is more familiar with distributed tests, @hendrikmakait maybe?

2023-06-16 09:23 UTC, phofl commented on distributed/tests/test_client.py
> +    has_pyarrow = False
You can use 

```
pytest.importorskip("pyarrow")
```

here. That's a bit shorter and less complicated.

2023-06-16 09:47 UTC, hendrikmakait requested changes
Thanks, @detroyejr, for fixing this! The code looks good to me. I would like some improvements for the test case before approving this.

2023-06-16 09:47 UTC, hendrikmakait commented on distributed/tests/test_client.py
> +async def test_handle_null_partitions_p2p_shuffling(c, s, *workers):
Thanks for adding a test case for the original issue. We currently group all tests related to P2P-shuffling in `distributed/shuffle/tests/test_shuffle.py` for discovery, please move it there. I'd also suggest you take a look at `test_concurrent`. It should serve as a good boilerplate and might help you simplify your test case (for example, skipping tests if packages are not installed is already taken care of): https://github.com/dask/distributed/blob/c520f1cf652882dc15c7cb8faf456ce5dc26f478/distributed/shuffle/tests/test_shuffle.py#L180

To make sure everything works correctly, we should also test that the resulting dataframe matches the expected pandas dataframe. You can use `dask.dataframe.utils.assert_eq` for this.

2023-06-19 15:24 UTC, hendrikmakait reviewed
@detroyejr: Overall, the test looks great now, I only have one minor suggestion for improvement.

2023-06-19 15:24 UTC, hendrikmakait commented on distributed/shuffle/tests/test_shuffle.py
> +    assert dask.dataframe.utils.assert_eq(result, df)
The `assert` is not necessary, `assert_eq` already takes care of that and throws a meaningful `AssertionError`. I'd also suggest making use of the file-level import of `dask.dataframe` to make the assertion more readable.   

```suggestion
    dd.assert_eq(result, df)
```

2023-06-20 15:03 UTC, hendrikmakait approved these changes
Thanks, @detroyejr, great work! I've merged the latest `main` to avoid CI failures caused by upstream changes and will merge once CI is done and green-ish.

2023-06-20 15:05 UTC, detroyejr commented
Awesome, thanks for all your help!

2023-06-20 18:03 UTC, merged